name: Post to the Mastodon

on:
  workflow_dispatch:
    
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'npm'
    - run: npm ci
    - run: npx nodejsscript index.js
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
