name: Post to the Mastodon

on:
  workflow_dispatch:
    
jobs:
  main:
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts
        cache: 'npm'
    - run: npm ci
    - run: npx nodejsscript index.js
