name: Post to the Mastodon

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */6 * * *'
    
permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: lts/*
        cache: 'npm'
    - run: npm ci
    - run: npx nodejsscript cli.js mastodon --url 'https://front-end.social/' --token "${MASTODON_ACCESS_TOKEN}"
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
